### ISSUE TITLE
Kubernetes Third-Party Security Audit for 2025 (tracking issue)

### ISSUE THREAD

**Issue by reylejano** [kubernetes/sig-security#104]
Tracking issue for the Kubernetes third-party security audit for 2025:
- [x] Define audit scope and provide to the Open Source Technology Improvement Fund (OSTIF)
- [x] OSTIF Creates RFP
  - [x] SIG Security Third-Party Audit subproject reviews RFP
- [x] Vendor assessment
- [x] Release vendor selection
- [ ] Create private Slack channel for vendor and subproject
- [ ] Vendor conducts audit
  - [ ] Coordinate SME as contacts for vendor
- [ ] Send findings to SRC
- [ ] Findings review with SIG Security
- [ ] Publish findings

/sig security

**Comment by ritazh** [comment]
xref: https://github.com/kubernetes/sig-security/pull/105 add windows to scope

**Comment by sunstonesecure-robert** [comment]
also include the new threat model refresh @raesene

**Comment by sftim** [comment]
Aside: how about adding `/area audit` (label and associated Prow command)?

**Comment by TheFoxAtWork** [comment]
@reylejano i saw this closed, is it not yet scheduled ?

**Comment by sunstonesecure-robert** [comment]
Work is in progress…there is an outline of dates that maybe OSTIF can share here?
