### ISSUE TITLE
Kubernetes Third-Party Security Audit for 2021-22 (tracking issue)

### ISSUE THREAD

**Issue by reylejano** [kubernetes/sig-security#13]
Tracking issue for the Kubernetes third-party security audit for 2021:
- [X] Create RFP
  - [X] Audit scope
  - [X] Finalize dates: RFP opening and closing dates, question period, vendor selection
  - [X] Complete question period and publish questions & replies to RFP 
- [x] Vendor assessment
  - [x] Assemble vendor assessment group
  - [x] Create private Google group
- [x] Release vendor selection
- [x] Publish findings

/sig security
/label external-audit

**Comment by PurelyApplied** [comment]
These things take time, triage-bot.

/remove-lifecycle stale

Although, given the bleed-over, the this could be renamed `* for 2022`.

**Comment by PushkarJ** [comment]
/retitle Kubernetes Third-Party Security Audit for 2021-22 (tracking issue)

**Comment by reylejano** [comment]
This issue is complete :tada: with the merge of PR https://github.com/kubernetes/sig-security/pull/87
and publishing of the CNCF blog https://www.cncf.io/blog/2023/04/19/new-kubernetes-security-audit-complete-and-open-sourced/

/close

**Comment by reylejano** [comment]
Findings published at https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf
