### ISSUE TITLE
[Umbrella] Security Assessment Process for Kubernetes sub-projects

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#2]
**Goal**: Define, execute and improve on a community driven security assessment process for kubernetes sub-projects, which is self-service and welcomes beginners without prior security background to engage and contribute

## Background

CNCF TAG Security has a well established [process](https://github.com/cncf/tag-security/tree/main/assessments) for project maintainers to engage them in a security review process. However, typically the scope is limited to CNCF projects _not_ sub-projects of graduated projects like Kubernetes. In case of Kubernetes, SIG Security is taking up this responsibility to work within the project community through self-assessments as a partnership between maintainers and SIG Security Members

## Scope

- [X] Identify first project as a pilot for this process (Cluster API)
- [X] Create a draft template for self-assessment and gather feedback ([Self-Assessment Template](https://docs.google.com/document/d/1urwOa0lhzbA2XsFyDZrg2x5Fg_yEHCzSu740FDhn_go/edit))
- [x] Publish draft template after incorporating feedback, in markdown under `kubernetes/sig-security`
- [x] Publish a task list that covers the entire security assessment process (channel creation, identifying contributors, presenting and resolving findings, etc.): https://github.com/kubernetes/sig-security/blob/main/sig-security-assessments/Documentation/recipe-book.md
- [x] Create label `area/security-assessment` to allow filtering of these requests (https://github.com/kubernetes/test-infra/pull/23070)
- [x] Create a Github Issue Template to allow anyone to request a security assessment for a sub-project (https://github.com/kubernetes/community/pull/5922)
- [x] Perform retrospective on the process and identify improvements after every assessment: https://github.com/cncf/tag-security/issues/957

## Related Issues

Cluster API pilot discussion: https://github.com/cncf/tag-security/issues/603 
Cluster API tracker: https://github.com/kubernetes/community/issues/5814
Admission controller: https://github.com/cncf/tag-security/issues/731

/assign @PushkarJ
cc @rficcaglia @reylejano @savitharaghunathan @kubernetes/sig-security-leads 
/sig security

**Comment by PushkarJ** [comment]
/area security-assessment

(Trying out the new label that was merged today)

**Comment by PushkarJ** [comment]
@aladewberry I updated the description to cover links to all the tasks in the list and marked them as done. Since we have a new sub-project that is going places and making things secure, the issue has served its purpose. 

So, I am closing this issue since we can track future self-assessments through their own issues like you are already doing for vsphere-csi-driver #21 and #40 for cluser-api

Feel free to re-open if you disagree :) (Just doing this as part of backlog clearing on my end)
