### ISSUE TITLE
Create a security checklist for deploying a cluster

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/sig-security#28]
While there are many checklists available, this could be a recommended checklist for ensuring security in Kubernetes clusters. 

Overall guidance:
* Avoid 3rd party tools
* Avoid linking to documentation outside of K8s website (as it might not be maintained)
* If you identify a section that needs more documentation, please create an issue and tag sig-security.

Potential checklist sections:
Cluster level
- [ ] AuthN & AuthZ
- [ ] Network security - @Skybound1
- [ ] Pod security - @mtardy
- [ ] Pod placement - @Skybound1
- [ ] Secrets - @Skybound1
- [ ] Container & Image scanning - @p4ck3t0
- [ ] Enabling seccomp - @mtardy

Application/workload:

- [ ] Ingress/Network config
- [ ] RBAC

**Comment by mtardy** [comment]
Thanks Savitha! I think I would be glad to write the part about PodSecurity, I took a look at it recently ([here](https://github.com/kubernetes/website/pull/31602)) and found it very convenient to use! I could also try to handle the "Enabling seccomp" part also but don't want to take all the good stuff 😄!

I think we could discuss this at the next security documentation meeting, but for this checklist, do you envision something complete in and of itself or a short descriptions and references to the documentation?

**Comment by savitharaghunathan** [comment]
> I think we could discuss this at the next security documentation meeting, but for this checklist, do you envision something complete in and of itself or a short descriptions and references to the documentation?

Thanks @mtardy :) I am thinking that we will have a one liner and also a link to documentation if available. WDYT?

**Comment by mtardy** [comment]
Yes I agree! I don't think it would be a good idea to repeat what is already well presented in the documentation, but a central page to refer to all the good security features of Kubernetes with a one liner to introduce them and why they are important would be great!

**Comment by Skybound1** [comment]
I'm happy to pick up Network Security and Secrets. Also, I agree on taking the approach of making this more summary based and linking to relevant detailed guides.

**Comment by p4ck3t0** [comment]
I can do the Container & Image scanning part. Also agreeing on the summary based approach.

**Comment by p4ck3t0** [comment]
What about confidential Kubernetes? I could link some interesting stuff to some open source projects, I was involved in.

**Comment by savitharaghunathan** [comment]
> What about confidential Kubernetes? I could link some interesting stuff to some open source projects, I was involved in.

@p4ck3t0 is confidential Kubernetes a part of the Kubernetes ecosystem or core concepts? We want to limit this checklist to that and avoid third party recommendations in order to keep it vendor neutral.

**Comment by p4ck3t0** [comment]
> @p4ck3t0 is confidential Kubernetes a part of the Kubernetes ecosystem or core concepts? We want to limit this checklist to that and avoid third party recommendations in order to keep it vendor neutral.

No it's not a core concept, I will focus on Container & Image scanning.

**Comment by savitharaghunathan** [comment]
> No it's not a core concept, I will focus on Container & Image scanning.


 @p4ck3t0 would you like to create a blog post for this topic? It sounds like a beneficial topic.

**Comment by p4ck3t0** [comment]
> @p4ck3t0 would you like to create a blog post for confidential Kubernetes? It sounds like a beneficial topic.

@savitharaghunathan sure I want to write a short blog post about it. I just need to see if I could do both, Confidential Kubernetes blogpost and Container & Image scanning checklist.

**Comment by Skybound1** [comment]
Based of the conversation in Slack, also happy to pick up pod placement :)

**Comment by savitharaghunathan** [comment]
> Based of the conversation in Slack, also happy to pick up pod placement :)

Added a new task item and assigned it to you. Thanks, @Skybound1 :)

**Comment by cailynse** [comment]
@Skybound1 - I'd love to pair on the Network Security section if you're up for it!

**Comment by sftim** [comment]
@mtardy, https://github.com/kubernetes/website/pull/34873 added some sound advice - you might want to add that to the checklist too.

**Comment by sftim** [comment]
> do you think we should make another warning directly on the checklist?

I'm fine either way. I'm not sure how you frame a common misunderstanding as a checklist item, but if there's a way then I'm all for it.

**Comment by sftim** [comment]
I noticed some security advice in https://github.com/kubernetes/website/pull/35511 and thought I'd mention it here.

**Comment by sftim** [comment]
We created a [checklist](https://kubernetes.io/docs/concepts/security/security-checklist/).

/close

(folks can reopen if they don't agree this is resolved)

**Comment by sftim** [comment]
I like the idea of making another issue to track further improvements.

**Comment by mtardy** [comment]
> (folks can reopen if they don't agree this is resolved)

You are correct I should be more confident 😄
