### ISSUE TITLE
[Umbrella] Artifact Vulnerability Scanning and Triage Policy

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#3]
**Goal**: Implement automated scanning capabilities that are tool agnostic for identifying vulnerabilities in Kubernetes related artifacts, followed by a documented private triage process to resolve the identified vulnerability, with a programmable way for Kubernetes users to consume this vulnerability information. 

## Background
Over the years, multiple different community members in Security Response Committee (formerly PSC), SIG Release, Architecture, Security, Auth have contributed to several standalone efforts related to vulnerability management for https://github.com/kubernetes/kubernetes. We have made tremendous progress but there are still some opportunities to improve  :-)

## Scope
This issue is created to act as a single place to find current state of the work, in progress and planned work that fall in the overall theme of vulnerability management of Kubernetes artifacts. In scope artifacts include but are not limited to build time dependencies and container images. Adding any missing issues or related work as a comment is encouraged :-) 

### Build time Dependencies

- [x] Implement automated scanning with prow and test-grid for k/k HEAD (main branch) (https://github.com/kubernetes/kubernetes/issues/101528)
- [X] Parsing improvements (https://github.com/kubernetes/test-infra/pull/22756)
- [X] Ensure scan fails when a vulnerability is found (https://github.com/kubernetes/test-infra/pull/22833)
- [x] https://github.com/kubernetes/test-infra/issues/23112
- [ ] #95 

### Container Images

- [x] https://github.com/kubernetes/sig-security/issues/4
- [x] Explore and identify scanners that can detect vulnerabilities in distroless++ images
- [x] Explore using SBOM to programmatically get a list of images in each kubernetes release (https://github.com/kubernetes/release/pull/2095)
- [x] Implement automated scanning with prow and test-grid for k/k HEAD
- [x] Ensure scan fails when a vulnerability is found

### Ongoing Maintenance

- https://github.com/kubernetes/test-infra/pull/27309
- https://github.com/kubernetes/test-infra/pull/26777
- https://github.com/kubernetes/test-infra/pull/24857
- https://github.com/kubernetes/test-infra/pull/24446

## Triage Policy Definition and Implementation

- [ ] Solicit feedback from SRC and SIG Security Co-chairs for Triage and Resolution policy (https://github.com/kubernetes/community/pull/5853)
- [X] Create a new group for private triage (https://github.com/kubernetes/k8s.io/pull/2342)
- [x] Drive an end to end triage for an identified vulnerability to resolution
- [ ] Update the triage and resolution policy based on end to end experience
- [ ] https://github.com/kubernetes/sig-security/issues/1
- [ ] Define and Measure mean time to triage, false positive rate for each identified vulnerability
- [ ] Create a rotating triage role for taking action on identified vulnerability

## Related Issues and PRs

- Original issue to track kubernetes build time dependencies: https://github.com/kubernetes/community/issues/2992
- CVE RSS feed broken: https://github.com/kubernetes/website/issues/29142
- Request for base image patching: https://github.com/kubernetes/release/issues/1833
- Examples of CVE fixes:
  - Build time dependency bumps: https://github.com/kubernetes/kubernetes/issues/117094
  - Debian base image bumps: https://github.com/kubernetes/kubernetes/pull/102302
  - Distroless base image bumps: https://github.com/kubernetes/kubernetes/pull/100566
  - Build time dependency bumps: https://github.com/kubernetes/kubernetes/issues/100401
- CNCF TAG Security discussion: https://github.com/cncf/tag-security/issues/170

/sig security release architecture auth
/area config testing code-organization dependency release-eng release-eng/security
/committee product-security
/kind feature

**Comment by sherine-k** [comment]
In May 2026, [a kep](https://docs.google.com/document/d/1JdCYfwBU-1eoDSKa0lFL_VfVr3du2-gDT3RhILETUrQ/edit?tab=t.0) was proposed and introduced to SIG Testing and SIG Release. 
With little feedbacks and reviews so far, we are parking this investigation.
